- platform: mqtt
  name: "Digoo DG-SP202 #1"
  command_topic: "cmnd/dgsp202/power1"
  state_topic: "stat/dgsp202/POWER1"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  retain: false
- platform: mqtt
  name: "Digoo DG-SP202 #2"
  command_topic: "cmnd/dgsp202/power2"
  state_topic: "stat/dgsp202/POWER2"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  retain: false