- id: open_front_door
  alias: 1. Front door opened
  trigger:
  - entity_id: binary_sensor.door_window_sensor_158d0001f3467a
    from: 'off'
    platform: state
    to: 'on'
  action:
  - data:
      message: The front door of the house was opened!
      title: Door is open
    service: notify.pushbullet
  - data:
      message: The front door of the house was opened!
      title: Door is open
    service: notify.mailgun
- id: restart_home_assistant
  alias: 2. Restart Home Assistant
  trigger:
  - platform: time
    at: 03:00:00
  condition:
  - condition: time
    weekday:
    - sun
    - mon
    - tue
    - wed
    - thu
    - fri
    - sat
  action:
  - service: homeassistant.restart
- id: backup_home_assistant
  alias: 3. Backup Home Assistant
  trigger:
  - at: 04:00:00
    platform: time
  condition:
  - condition: time
    weekday:
    - sun
    - mon
    - tue
    - wed
    - thu
    - fri
    - sat
  action:
  - alias: Backup Home Assistant
    data:
      name: Automated Backup {{ now().strftime('%Y-%m-%d') }}
    service: hassio.snapshot_full
  - delay: '00:20'
  - alias: Upload Home Assistant Backup
    data:
      addon: 7be23ff5_dropbox_sync
      input:
        command: upload
    service: hassio.addon_stdin
# - id: upload_home_assistant_backup
#   alias: 4. Upload Home Assistant Backup
#   trigger:
#   - at: 04:30:00
#     platform: time
#   condition:
#   - condition: time
#     weekday:
#     - sun
#     - mon
#     - tue
#     - wed
#     - thu
#     - fri
#     - sat
#   action:
#   - alias: Upload Home Assistant Backup
#     data:
#       addon: 7be23ff5_dropbox_sync
#       input:
#         command: upload
#     service: hassio.addon_stdin