homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: 35.325
  longitude: 25.1306
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 0
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Athens
  # Customization file
  customize: !include customize.yaml

# Show links to resources in log and frontend
#introduction:

# Enables the frontend
frontend:

panel_iframe:
  configurator:
    title: Configurator
    icon: mdi:wrench
    url: !secret configurator_url
  ide:
    title: IDE
    icon: mdi:code-braces
    url: !secret ide_url
    
mqtt:
  broker: core-mosquitto
  username: !secret mqtt_username
  password: !secret mqtt_password
  
mailgun:
  domain: !secret mailgun_domain
  api_key: !secret mailgun_key
  
# media_player:
#   - platform: volumio
#     host: 192.168.1.100
#     port: 3000
  
# Example configuration.yaml entry
notify:
  - name: pushbullet
    platform: pushbullet
    api_key: !secret pushbullet_api_key
  - name: mailgun
    platform: mailgun
    recipient: !secret mailgun_recipient
    sender: !secret mailgun_sender
  - name: pushetta
    platform: pushetta
    api_key: !secret pushetta_api_key
    channel_name: !secret pushetta_channel

# You can leave MAC empty if you only have one gateway.
xiaomi_aqara:
  discovery_retry: 5
  gateways:
    - key: !secret gateway_key

# Enables configuration UI
config:

http:
  # Secrets are defined in the file secrets.yaml
  api_password: !secret http_password
  # Uncomment this if you are using SSL/TLS, running in Docker container, etc.
  # base_url: example.duckdns.org:8123
  base_url: !secret base_url
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:

light: !include light.yaml

switch: !include switch.yaml

#weather:
#  - platform: yweather

# Weather prediction
sensor: !include sensor.yaml

# Text to speech
tts:
  - platform: google

# Cloud
cloud:

cover: !include cover.yaml
group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
