- platform: mqtt
  name: "Sonoff Switch 01 Temp"
  state_topic: "tele/sonoff1/SENSOR"
  value_template: "{{ value_json['SI7021'].Temperature }}"
  unit_of_measurement: "°C"
- platform: mqtt
  name: "Sonoff Switch 01 Humidity"
  state_topic: "tele/sonoff1/SENSOR"
  value_template: "{{ value_json['SI7021'].Humidity }}"
  unit_of_measurement: "%"
- platform: yr