# - platform: mqtt
#   name: "Sonoff Switch 01"
#   command_topic: "cmnd/sonoff1/power"
#   state_topic: "stat/sonoff1/POWER"
#   qos: 1
#   payload_on: "ON"
#   payload_off: "OFF"
#   retain: true
- platform: mqtt
  name: "Sonoff Switch 02"
  command_topic: "cmnd/sonoff2/power"
  state_topic: "stat/sonoff2/POWER"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  retain: true
# - platform: mqtt
#   name: "Sonoff Switch 03"
#   command_topic: "cmnd/sonoff3/power"
#   state_topic: "stat/sonoff3/POWER"
#   qos: 1
#   payload_on: "ON"
#   payload_off: "OFF"
#   retain: true
# - platform: mqtt
#   name: "Sonoff Switch 04"
#   command_topic: "cmnd/sonoff4/power"
#   state_topic: "stat/sonoff4/POWER"
#   qos: 1
#   payload_on: "ON"
#   payload_off: "OFF"
#   retain: true
# - platform: mqtt
#   name: "SWITCH"
#   command_topic: "ha/switch1"
#   state_topic: "ha/switch1"
#   qos: 0
#   payload_on: "ON"
#   payload_off: "OFF"
#   optimistic:
#   retain: true
# - platform: mqtt
#   name: "ESP8266 Switch"
#   command_topic: "cmnd/sonoff99/power"
#   state_topic: "stat/sonoff99/POWER"
#   qos: 1
#   payload_on: "ON"
#   payload_off: "OFF"
#   retain: true
- platform: mqtt
  name: "Blitzwolf SHP2"
  command_topic: "cmnd/bwshp2/power"
  state_topic: "stat/bwshp2/POWER"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  retain: true