- platform: template
  sensors:
    door_sensor_1_battery_level:
            friendly_name: 'Front Door Sensor'
            value_template: "{{ states.binary_sensor.door_window_sensor_158d0001f3467a.attributes.battery_level|default(-1)|int if states.binary_sensor.door_window_sensor_158d0001f3467a is not none }}"
            unit_of_measurement: '%'
            icon_template: '{% if states.binary_sensor.door_window_sensor_158d0001f3467a.attributes.battery_level == 100 %}
                               mdi:battery
                            {% elif states.binary_sensor.door_window_sensor_158d0001f3467a.attributes.battery_level >= 90 %}
                               mdi:battery-90
                            {% elif states.binary_sensor.door_window_sensor_158d0001f3467a.attributes.battery_level >= 80 %}
                               mdi:battery-80
                            {% elif states.binary_sensor.door_window_sensor_158d0001f3467a.attributes.battery_level >= 70 %}
                               mdi:battery-70
                            {% elif states.binary_sensor.door_window_sensor_158d0001f3467a.attributes.battery_level >= 60 %}
                               mdi:battery-60
                            {% elif states.binary_sensor.door_window_sensor_158d0001f3467a.attributes.battery_level >= 50 %}
                               mdi:battery-50
                            {% elif states.binary_sensor.door_window_sensor_158d0001f3467a.attributes.battery_level >= 40 %}
                               mdi:battery-40
                            {% elif states.binary_sensor.door_window_sensor_158d0001f3467a.attributes.battery_level >= 30 %}
                               mdi:battery-30
                            {% elif states.binary_sensor.door_window_sensor_158d0001f3467a.attributes.battery_level >= 20 %}
                               mdi:battery-20
                            {% elif states.binary_sensor.door_window_sensor_158d0001f3467a.attributes.battery_level >= 10 %}
                               mdi:battery-10
                            {% else %}
                               battery-outline
                            {% endif %}'
    door_sensor_2_battery_level:
            friendly_name: 'Other Door sensor'
            value_template: "{{ states.binary_sensor.door_window_sensor_158d0001dcaff1.attributes.battery_level|default(-1)|int if states.binary_sensor.door_window_sensor_158d0001dcaff1 is not none }}"
            unit_of_measurement: '%'
            icon_template: '{% if states.binary_sensor.door_window_sensor_158d0001dcaff1.attributes.battery_level == 100 %}
                               mdi:battery
                            {% elif states.binary_sensor.door_window_sensor_158d0001dcaff1.attributes.battery_level >= 90 %}
                               mdi:battery-90
                            {% elif states.binary_sensor.door_window_sensor_158d0001dcaff1.attributes.battery_level >= 80 %}
                               mdi:battery-80
                            {% elif states.binary_sensor.door_window_sensor_158d0001dcaff1.attributes.battery_level >= 70 %}
                               mdi:battery-70
                            {% elif states.binary_sensor.door_window_sensor_158d0001dcaff1.attributes.battery_level >= 60 %}
                               mdi:battery-60
                            {% elif states.binary_sensor.door_window_sensor_158d0001dcaff1.attributes.battery_level >= 50 %}
                               mdi:battery-50
                            {% elif states.binary_sensor.door_window_sensor_158d0001dcaff1.attributes.battery_level >= 40 %}
                               mdi:battery-40
                            {% elif states.binary_sensor.door_window_sensor_158d0001dcaff1.attributes.battery_level >= 30 %}
                               mdi:battery-30
                            {% elif states.binary_sensor.door_window_sensor_158d0001dcaff1.attributes.battery_level >= 20 %}
                               mdi:battery-20
                            {% elif states.binary_sensor.door_window_sensor_158d0001dcaff1.attributes.battery_level >= 10 %}
                               mdi:battery-10
                            {% else %}
                               battery-outline
                            {% endif %}'
    temperature_sensor_1_battery_level:
            friendly_name: "Katerina's Temperature/Humidity Sensor"
            value_template: "{{ states.sensor.temperature_158d000149caa5.attributes.battery_level|default(-1)|int if states.sensor.temperature_158d000149caa5 is not none }}"
            unit_of_measurement: '%'
            icon_template: '{% if states.sensor.temperature_158d000149caa5.attributes.battery_level == 100 %}
                               mdi:battery
                            {% elif states.sensor.temperature_158d000149caa5.attributes.battery_level >= 90 %}
                               mdi:battery-90
                            {% elif states.sensor.temperature_158d000149caa5.attributes.battery_level >= 80 %}
                               mdi:battery-80
                            {% elif states.sensor.temperature_158d000149caa5.attributes.battery_level >= 70 %}
                               mdi:battery-70
                            {% elif states.sensor.temperature_158d000149caa5.attributes.battery_level >= 60 %}
                               mdi:battery-60
                            {% elif states.sensor.temperature_158d000149caa5.attributes.battery_level >= 50 %}
                               mdi:battery-50
                            {% elif states.sensor.temperature_158d000149caa5.attributes.battery_level >= 40 %}
                               mdi:battery-40
                            {% elif states.sensor.temperature_158d000149caa5.attributes.battery_level >= 30 %}
                               mdi:battery-30
                            {% elif states.sensor.temperature_158d000149caa5.attributes.battery_level >= 20 %}
                               mdi:battery-20
                            {% elif states.sensor.temperature_158d000149caa5.attributes.battery_level >= 10 %}
                               mdi:battery-10
                            {% else %}
                               battery-outline
                            {% endif %}'
    temperature_sensor_2_battery_level:
            friendly_name: 'Living Room Temperature/Humidity Sensor'
            value_template: "{{ states.sensor.temperature_158d0001c1504f.attributes.battery_level|default(-1)|int if states.sensor.temperature_158d0001c1504f is not none }}"
            unit_of_measurement: '%'
            icon_template: '{% if states.sensor.temperature_158d0001c1504f.attributes.battery_level == 100 %}
                               mdi:battery
                            {% elif states.sensor.temperature_158d0001c1504f.attributes.battery_level >= 90 %}
                               mdi:battery-90
                            {% elif states.sensor.temperature_158d0001c1504f.attributes.battery_level >= 80 %}
                               mdi:battery-80
                            {% elif states.sensor.temperature_158d0001c1504f.attributes.battery_level >= 70 %}
                               mdi:battery-70
                            {% elif states.sensor.temperature_158d0001c1504f.attributes.battery_level >= 60 %}
                               mdi:battery-60
                            {% elif states.sensor.temperature_158d0001c1504f.attributes.battery_level >= 50 %}
                               mdi:battery-50
                            {% elif states.sensor.temperature_158d0001c1504f.attributes.battery_level >= 40 %}
                               mdi:battery-40
                            {% elif states.sensor.temperature_158d0001c1504f.attributes.battery_level >= 30 %}
                               mdi:battery-30
                            {% elif states.sensor.temperature_158d0001c1504f.attributes.battery_level >= 20 %}
                               mdi:battery-20
                            {% elif states.sensor.temperature_158d0001c1504f.attributes.battery_level >= 10 %}
                               mdi:battery-10
                            {% else %}
                               battery-outline
                            {% endif %}'